package Capa_Presentacion;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Eduardo
 */
public class frmPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        InitStyles();
        aplicarTemaMac();
    }
    private void InitStyles() {
    // Define un tamaño de fuente atractivo
    int fontSize = 12; // Puedes ajustar el tamaño según sea necesario
    Color textColor = new Color(34, 34, 34); // Color de texto oscuro

    // Aplicar estilo a todos los lbl
    lbl1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, fontSize));
    lbl1.setForeground(textColor);

    lbl2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, fontSize));
    lbl2.setForeground(textColor);

    lbl3.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, fontSize));
    lbl3.setForeground(textColor);

    lbl4.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, fontSize));
    lbl4.setForeground(textColor);

    lbl5.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, fontSize));
    lbl5.setForeground(textColor);

    lbl6.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, fontSize));
    lbl6.setForeground(textColor);
    
    lbl7.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, fontSize));
    lbl7.setForeground(textColor);

    lbl8.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, fontSize));
    lbl8.setForeground(textColor);

    lbl9.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, fontSize));
    lbl9.setForeground(textColor);

    lbl10.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, fontSize));
    lbl10.setForeground(textColor);

    lbl11.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, fontSize));
    lbl11.setForeground(textColor);

    lbl12.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, fontSize));
    lbl12.setForeground(textColor);

    lbl13.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, fontSize));
    lbl13.setForeground(textColor);
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        lbl11 = new javax.swing.JLabel();
        lbl12 = new javax.swing.JLabel();
        lbl13 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(610, 540));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(610, 540));

        title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TECHNOVA.png"))); // NOI18N

        lbl1.setText("En TechNova, nos dedicamos a ofrecer equipos tecnológicos de alta calidad, diseñados para cubrir las ");

        lbl2.setText("necesidades de jugadores, profesionales y hogares. Con una amplia variedad de productos que y el uso ");

        lbl3.setText("doméstico, nuestra nuestra misión es proporcionar innovación tecnológica con un servicio excepcional.");

        lbl4.setText("Este sistema te permitirá gestionar de manera eficiente cada aspecto de nuestras operaciones. Las ");

        lbl5.setText("principales características incluyen:");

        lbl6.setText("• Control de usuarios: Gestión de accesos, permisos para garantizar la seguridad, organización de los");

        lbl8.setText("• Productos e inventarios: Control detallado del inventario y actualización en tiempo real a productos.");

        lbl9.setText("• Categorías y ventas: Organización de productos por categorías y administración de las ventas de manera ");

        lbl10.setText(" ágil y eficiente.");

        lbl11.setText("• Reportes: Generación de informes completos para evaluar el rendimiento de las ventas y el estado del");

        lbl12.setText("del inventario.");

        lbl13.setText("¡Gracias por confiar en TechNova, donde la tecnología y el futuro se encuentran!");

        lbl7.setText("empleados.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(479, 479, 479))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(507, 507, 507))
                    .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(536, 536, 536))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl3, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(lbl4, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl5, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(lbl6, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl7)
                .addGap(18, 18, 18)
                .addComponent(lbl8, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lbl9, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl10, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addGap(17, 17, 17)
                .addComponent(lbl11, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addComponent(lbl13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void aplicarTemaMac() {
        try {
            UIManager.setLookAndFeel(new FlatMacLightLaf());
            SwingUtilities.updateComponentTreeUI(this); // Actualiza la UI
        } catch (UnsupportedLookAndFeelException e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl13;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
