/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Capa_Presentacion;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import controlador.GeneradorDeReportes;

/**
 *
 * @author Eduardo
 */
public class frmReportes extends javax.swing.JPanel {

    private final GeneradorDeReportes generadorReportes = new GeneradorDeReportes();

    /**
     * Creates new form Producto
     */
    public frmReportes() {
        initComponents();
        aplicarTemaMac();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        btnReporteCategorias = new javax.swing.JButton();
        btnReporteProducto = new javax.swing.JButton();
        btnReporteCliente = new javax.swing.JButton();
        btnReporteDetalleVenta = new javax.swing.JButton();

        Background1.setBackground(new java.awt.Color(255, 255, 255));
        Background1.setPreferredSize(new java.awt.Dimension(610, 540));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel11.setForeground(new java.awt.Color(255, 255, 255));
        jPanel11.setPreferredSize(new java.awt.Dimension(590, 40));

        btnReporteCategorias.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnReporteCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CategoriaReport.png"))); // NOI18N
        btnReporteCategorias.setText("Reporte Categorias");
        btnReporteCategorias.setBorderPainted(false);
        btnReporteCategorias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReporteCategorias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReporteCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteCategoriasActionPerformed(evt);
            }
        });

        btnReporteProducto.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnReporteProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ProductoReport.png"))); // NOI18N
        btnReporteProducto.setText("Reporte Producto");
        btnReporteProducto.setBorderPainted(false);
        btnReporteProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReporteProducto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReporteProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteProductoActionPerformed(evt);
            }
        });

        btnReporteCliente.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnReporteCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ClienteReport.png"))); // NOI18N
        btnReporteCliente.setText("Reporte Cliente");
        btnReporteCliente.setBorderPainted(false);
        btnReporteCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReporteCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReporteCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteClienteActionPerformed(evt);
            }
        });

        btnReporteDetalleVenta.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnReporteDetalleVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VentasReport.png"))); // NOI18N
        btnReporteDetalleVenta.setText("Reporte Ventas");
        btnReporteDetalleVenta.setBorderPainted(false);
        btnReporteDetalleVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReporteDetalleVenta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReporteDetalleVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteDetalleVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReporteProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReporteCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReporteCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(btnReporteDetalleVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReporteCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(btnReporteCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReporteProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(btnReporteDetalleVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout Background1Layout = new javax.swing.GroupLayout(Background1);
        Background1.setLayout(Background1Layout);
        Background1Layout.setHorizontalGroup(
            Background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Background1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Background1Layout.setVerticalGroup(
            Background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Background1Layout.createSequentialGroup()
                .addContainerGap(292, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Background1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteCategoriasActionPerformed
        // TODO add your handling code here:
        generadorReportes.generarReporteCategorias();
    }//GEN-LAST:event_btnReporteCategoriasActionPerformed

    private void btnReporteClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteClienteActionPerformed
        // TODO add your handling code here:
        generadorReportes.generarReporteClientes();
    }//GEN-LAST:event_btnReporteClienteActionPerformed

    private void btnReporteProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteProductoActionPerformed
        // TODO add your handling code here:
        generadorReportes.generarReporteProductos();
    }//GEN-LAST:event_btnReporteProductoActionPerformed

    private void btnReporteDetalleVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteDetalleVentaActionPerformed
        // TODO add your handling code here:
        generadorReportes.generarReporteDetalleVentas();
    }//GEN-LAST:event_btnReporteDetalleVentaActionPerformed

    private void aplicarTemaMac() {
        try {
            UIManager.setLookAndFeel(new FlatMacLightLaf());
            SwingUtilities.updateComponentTreeUI(this); // Actualiza la UI
        } catch (UnsupportedLookAndFeelException e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background1;
    private javax.swing.JButton btnReporteCategorias;
    private javax.swing.JButton btnReporteCliente;
    private javax.swing.JButton btnReporteDetalleVenta;
    private javax.swing.JButton btnReporteProducto;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
